### ISSUE TITLE
Task list

### ISSUE THREAD

**Issue by gnuwilliam** [ellisonleao/megplay#2]
- [ ] Colisão dos bandAids com os postIts - @ellisonleao 
- [ ] Criar slider após a página principal (utilizar um modal box escurecendo o fundo, e um botão "pular") - @gnuwilliam
- [ ] Quando o player clicar no critério, exibir uma descrição do mesmo - @ellisonleao
